"""add_batch_links_and_download_archive_tables

Revision ID: 37dc6a4bbfdf
Revises: 5109abe4a177
Create Date: 2026-01-29 09:29:43.222078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37dc6a4bbfdf'
down_revision = '5109abe4a177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
